# This is a basic workflow to help testing against pushes and PRs

name: Hello from Test

# Controls when the action will run. It should trigger the workflow on push or pull request
# events but only for the test_ga_triggers branch
on:
  push:
    branches: [ test_ga_triggers ]
  pull_request:
    branches: [ test_ga_triggers ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world - from test_ga_triggers branch!i

